algoritmo "Eua"
// Função : Recebe a idade e informa se e maior de 21 anos
// Autor : Rodrigo loeps martins
// Data : 20/02/2014
// Seção de Declarações 
var
   idade: inteiro

inicio
// Seção de Comandos
    escreval(">>Programa para informar se sua idade e maior que 21 anos!<<")
    escreval("Informe sua idade")
    leia(idade)
    
    se (idade > 21) entao
    escreval("Voce e maior de 21 anos !")
    
    senao
    escreval("Voce e menor de 21 anos!")
    
    fimse
fimalgoritmo
