algoritmo "Intercambiar"
// Função : Intercambiar valores
// Autor : Rodrigo lopes martins
// Data : 18/02/2014
// Seção de Declarações 
var
   a: inteiro
   b: inteiro
   c: inteiro
   d: inteiro

inicio
// Seção de Comandos 
   escreval("Valores iniciais")
   a<-5
   escreval(a)
   b<-7
   escreval(b)
   c<-12
   escreval(c)
   
   d<-a
   a<-b
   b<-c
   c<-d
   
   escreval("Fase final")
   
   escreval(a)
   escreval(b)
   escreval(c)
   
   escreva()
fimalgoritmo
