algoritmo "Area quadrado"
// Função :Area quadrado
// Autor : Rodrigo lopes martins
// Data : 18/02/2014
// Seção de Declarações 
var
   LadoA: inteiro
   LadoB: inteiro

inicio
// Seção de Comandos
   escreval("Digite o valor la primeiro lado:")
   leia(LadoA)
   escreval("Digite o valor do segundo lado:")
   leia(LadoB)
   
   escreva("O valor da area do quadrado e:", LadoA * LadoB)
fimalgoritmo
